name: barubatu_3_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+10

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ^3.38.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter:
  settings_ui: ^2.0.2
  url_launcher: ^6.3.2
  in_app_review: ^2.0.11
  flutter_screenutil: 5.9.3
  awesome_dialog: ^3.3.0
  flutter_image_slideshow: ^0.1.6
  panara_dialogs: ^0.1.5
  get: ^4.7.3
  shared_preferences: ^2.5.4
  audioplayers: ^6.5.1
  provider: ^6.1.5+1
  enum_to_string: ^2.2.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon/icon.png"
  adaptive_icon_foreground: "assets/launcher_icon/icon.png"

flutter_native_splash:
  image: 'assets/images/splash.png'
  color_dark: '#ffffff'
  image_dark: 'assets/images/splash.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/images/splash.png'
    icon_background_color_dark: '#ffffff'
    image_dark: 'assets/images/splash.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/home/