name: barubatu_3_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+10

environment:
#  sdk: ">=2.12.0 <3.0.0"
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter:
  settings_ui: ^2.0.2
  url_launcher: ^6.0.18
  in_app_review: ^2.0.4
  animated_text_kit: ^4.2.1
  flutter_screenutil: 5.5.3+2
  flutter_animator: ^3.2.1
  awesome_dialog: ^2.2.1
  new_version: ^0.3.0
  flutter_image_slideshow: ^0.1.2
  panara_dialogs: ^0.1.5
  import_sorter: ^4.6.0
  get: ^4.6.1
  shared_preferences: ^2.2.2
  enum_to_string: ^2.2.1
  audioplayers: ^0.20.1


  google_mobile_ads: ^1.3.0
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.1.10
  flutter_native_splash: ^2.1.3+1

dependency_overrides:
  # Flutter 3.7 / Dart 2.19 系に合わせた互換バージョン固定
  win32: 2.4.1
  package_info_plus: 1.4.3+1
  package_info_plus_windows: 1.0.5
  package_info_plus_linux: 1.0.5
  package_info_plus_macos: 1.3.0
  package_info_plus_platform_interface: 1.0.2
  vector_math: 2.1.4
  material_color_utilities: 0.2.0
  characters: 1.2.1
  collection: 1.17.0
  meta: 1.8.0
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon/icon.png"
  adaptive_icon_foreground: "assets/launcher_icon/icon.png"

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/images/splash.png'
  color_dark: '#ffffff'
  image_dark: 'assets/images/splash.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/images/splash.png'
    icon_background_color_dark: '#ffffff'
    image_dark: 'assets/images/splash.png'

flutter:

  uses-material-design: true

  assets:
    - assets/images/dialog.png
    - assets/images/game.gif
    - assets/images/gold1.png
    - assets/images/gold2.png
    - assets/images/gold3.png
    - assets/images/gold4.png
    - assets/images/gold5.png

    - assets/images/grey1.png
    - assets/images/grey2.png
    - assets/images/grey3.png
    - assets/images/grey4.png
    - assets/images/grey5.png

    - assets/images/tap.mp3
    - assets/images/background.mp3
    - assets/images/trophy_b.mp3
    - assets/images/game_tap.mp3
    - assets/images/game_clear.mp3
    - assets/images/no_game_clear.mp3
    - assets/images/game_bgm.mp3